# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.org_detail import OrgDetail


class TestOrgDetail(unittest.TestCase):
    """OrgDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgDetail:
        """Test OrgDetail
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrgDetail`
        """
        model = OrgDetail()
        if include_optional:
            return OrgDetail(
                id = '',
                members = [
                    xleap._client.models.org_detail_members_inner.OrgDetail_members_inner(
                        id = 56, 
                        username = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = ''
            )
        else:
            return OrgDetail(
                members = [
                    xleap._client.models.org_detail_members_inner.OrgDetail_members_inner(
                        id = 56, 
                        username = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', )
                    ],
                name = '',
        )
        """

    def testOrgDetail(self):
        """Test OrgDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
