# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.list_org_lists200_response import ListOrgLists200Response


class TestListOrgLists200Response(unittest.TestCase):
    """ListOrgLists200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOrgLists200Response:
        """Test ListOrgLists200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListOrgLists200Response`
        """
        model = ListOrgLists200Response()
        if include_optional:
            return ListOrgLists200Response(
                next = '',
                previous = '',
                results = [
                    xleap._client.models.org_list.OrgList(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', )
                    ]
            )
        else:
            return ListOrgLists200Response(
        )
        """

    def testListOrgLists200Response(self):
        """Test ListOrgLists200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
