# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.list_metrics_datas200_response import (
    ListMetricsDatas200Response,
)


class TestListMetricsDatas200Response(unittest.TestCase):
    """ListMetricsDatas200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMetricsDatas200Response:
        """Test ListMetricsDatas200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListMetricsDatas200Response`
        """
        model = ListMetricsDatas200Response()
        if include_optional:
            return ListMetricsDatas200Response(
                next = '',
                previous = '',
                results = [
                    xleap._client.models.metrics.Metrics(
                        id = 56, 
                        query = '', 
                        context = '', )
                    ]
            )
        else:
            return ListMetricsDatas200Response(
        )
        """

    def testListMetricsDatas200Response(self):
        """Test ListMetricsDatas200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
