# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.token_obtain import TokenObtain


class TestTokenObtain(unittest.TestCase):
    """TokenObtain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenObtain:
        """Test TokenObtain
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TokenObtain`
        """
        model = TokenObtain()
        if include_optional:
            return TokenObtain(
                username = '',
                password = ''
            )
        else:
            return TokenObtain(
                username = '',
                password = '',
        )
        """

    def testTokenObtain(self):
        """Test TokenObtain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
