# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.ml_model import MLModel


class TestMLModel(unittest.TestCase):
    """MLModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MLModel:
        """Test MLModel
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MLModel`
        """
        model = MLModel()
        if include_optional:
            return MLModel(
                id = '',
                name = '',
                url = '',
                requests_count = 0,
                cost = '',
                status = 'active'
            )
        else:
            return MLModel(
                name = '',
                url = '',
                requests_count = 0,
                cost = '',
                status = 'active',
        )
        """

    def testMLModel(self):
        """Test MLModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
