# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.project_create_config import ProjectCreateConfig


class TestProjectCreateConfig(unittest.TestCase):
    """ProjectCreateConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateConfig:
        """Test ProjectCreateConfig
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProjectCreateConfig`
        """
        model = ProjectCreateConfig()
        if include_optional:
            return ProjectCreateConfig(
                metric_name_map = xleap._client.models.metric_name_map.metric_name_map(),
                transformer_name = '',
                topics = [
                    ''
                    ],
                nlp_scores = [
                    ''
                    ],
                rouge_type = '',
                scores = [
                    ''
                    ]
            )
        else:
            return ProjectCreateConfig(
                metric_name_map = xleap._client.models.metric_name_map.metric_name_map(),
                transformer_name = '',
                topics = [
                    ''
                    ],
                nlp_scores = [
                    ''
                    ],
                rouge_type = '',
                scores = [
                    ''
                    ],
        )
        """

    def testProjectCreateConfig(self):
        """Test ProjectCreateConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
