# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.org_detail_members_inner import OrgDetailMembersInner


class TestOrgDetailMembersInner(unittest.TestCase):
    """OrgDetailMembersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgDetailMembersInner:
        """Test OrgDetailMembersInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrgDetailMembersInner`
        """
        model = OrgDetailMembersInner()
        if include_optional:
            return OrgDetailMembersInner(
                id = 56,
                username = '',
                first_name = '',
                last_name = '',
                email = ''
            )
        else:
            return OrgDetailMembersInner(
                username = '',
        )
        """

    def testOrgDetailMembersInner(self):
        """Test OrgDetailMembersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
