# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xleap._client.models.list_ml_models200_response import ListMLModels200Response


class TestListMLModels200Response(unittest.TestCase):
    """ListMLModels200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMLModels200Response:
        """Test ListMLModels200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListMLModels200Response`
        """
        model = ListMLModels200Response()
        if include_optional:
            return ListMLModels200Response(
                next = '',
                previous = '',
                results = [
                    xleap._client.models.ml_model.MLModel(
                        id = '', 
                        name = '', 
                        url = '', 
                        requests_count = 0, 
                        cost = '', 
                        status = 'active', )
                    ]
            )
        else:
            return ListMLModels200Response(
        )
        """

    def testListMLModels200Response(self):
        """Test ListMLModels200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
