name: docs - build and deploy

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    working-directory: ./docs

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.16

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-cache-${{ hashFiles('bun.lockb') }}

      - name: Install dependencies
        run: bun install

      # - name: Deploy to GitHub Pages
      #   env:
      #     GIT_USER: pritamsoni-hsr
      #     GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.email "$GIT_USER@users.noreply.github.com"
      #     git config --global user.name $GIT_USER
      #     echo "machine github.com login $GIT_USER password $GIT_PASSWORD" > ~/.netrc
      #     # build and deploy
      #     bun run build
      #     bun run deploy

      - name: Build website
        run: bun run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
